# Generated by Django 3.2.3 on 2021-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedUser',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('searched', models.IntegerField(default=1)),
            ],
        ),
    ]
